"""report assignment + expiration

Revision ID: 68154b3fbb6d
Revises: d1a1b440aa14
Create Date: 2022-10-16 11:59:03.430470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68154b3fbb6d'
down_revision = 'd1a1b440aa14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.add_column('location', sa.Column('report_expires', sa.DateTime(), nullable=True))
    op.add_column('location', sa.Column('reported_by', sa.Integer(), nullable=True))
    op.drop_constraint('location_reviewed_by_fkey', 'location', type_='foreignkey')
    op.create_foreign_key(None, 'location', 'user', ['reported_by'], ['id'])
    op.drop_column('location', 'reviewed_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.create_foreign_key('location_reviewed_by_fkey', 'location', 'user', ['reviewed_by'], ['id'])
    op.drop_column('location', 'reported_by')
    op.drop_column('location', 'report_expires')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
