"""cascade strategies

Revision ID: c7da3587db52
Revises: 6055a1941c2a
Create Date: 2022-10-16 21:44:50.951774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7da3587db52'
down_revision = '6055a1941c2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('spatial_ref_sys')
    op.drop_constraint('location_reported_by_fkey', 'location', type_='foreignkey')
    op.create_foreign_key(None, 'location', 'user', ['reported_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint('sessionhistory_user_id_fkey', 'sessionhistory', type_='foreignkey')
    op.create_foreign_key(None, 'sessionhistory', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('user_organization_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'organization', ['organization'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_organization_fkey', 'user', 'organization', ['organization'], ['id'])
    op.drop_constraint(None, 'sessionhistory', type_='foreignkey')
    op.create_foreign_key('sessionhistory_user_id_fkey', 'sessionhistory', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'location', type_='foreignkey')
    op.create_foreign_key('location_reported_by_fkey', 'location', 'user', ['reported_by'], ['id'])
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('(srid > 0) AND (srid <= 998999)', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
